### ISSUE TITLE
RM Bug: Custom AppDelegate parent doesn't work

### ISSUE THREAD

**Issue by jamonholmgren** [clearsightstudio/ProMotion#116]
https://twitter.com/codefriar/status/341595361619636225

Need to allow:

```ruby
class AppDelegate < SomeOtherDelegate
  include PM::DelegateHelper
  def on_load(app, options)
    # ...
  end
end
```

**Comment by markrickert** [comment]
Can we change the code to no longer have to do this and remove the comments? https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/delegate/delegate_parent.rb

**Comment by jamonholmgren** [comment]
Yeah, let's do that in ProMotion 3.
