### ISSUE TITLE
PM::InfiniteTableScreen -- NSFetchedResultsController or roll our own?

### ISSUE THREAD

**Issue by jamonholmgren** [clearsightstudio/ProMotion#466]
`PM::TableScreen` is great for displaying a list view or menu, but if the dataset starts getting large or is not available in one chunk it can have an adverse effect on performance.

In some cases, developers use an `NSFetchedResultsController` to manage the data and return it to the table view. Mainly when they're working with CoreData. However, this isn't appropriate in all cases.

I'd like to explore either adapting `NSFetchedResultsController` to work with a variety of data sources *or* build our own implementation that works within `PM::TableScreen`.

In the coming weeks, I'll play with various API designs and implementations and discuss them in this thread. **Please** chime in if you have input!

cc @matthewsinclair @wndxlori

**Comment by holgersindbaek** [comment]
@jamonholmgren How's it going with the infinite tableview? @matthewsinclair How did you solve it?

**Comment by jamonholmgren** [comment]
I haven't gotten very far. We'll eventually have it, though.

**Comment by markrickert** [comment]
Posting here for future knowledge seekers - this is being implemented in a slightly modified way in [redpotion](https://github.com/infinitered/redpotion) and is close to completion. It uses CoreData and live table updating from core data notifications so all you'll have to do is add data to your db and it'll automatically keep going forever! (or at least until your data runs out)
