### ISSUE TITLE
longpressable and self.parent_screen

### ISSUE THREAD

**Issue by osterwood** [clearsightstudio/ProMotion#516]
Not sure why but this causes self.parent_screen to be nil:

```
class SelectTable < PM::TableScreen
  longpressable

  def model
    self.parent_screen.model
  end

end
```

while this works:

```
class SelectTable < PM::TableScreen
 
  def on_load
    self.make_longpressable()
  end

  def model
    self.parent_screen.model
  end

end
```

Long press events work the second way.  I don't know why `longpressable` causes clobbering of `self.parent_screen`.

**Comment by jamonholmgren** [comment]
Closing, feel free to update if it's still an issue.
