### ISSUE TITLE
remote_image in table cell broken

### ISSUE THREAD

**Issue by chrise86** [clearsightstudio/ProMotion#522]
# rubymotion 2.31
    # ProMotion 2.0.0

    def table_data
      [{
        cells: @posts.map do |p|
          {
            title: p["title"].kv_decodeHTMLCharacterEntities,
            action: :tap_post,
            arguments: { id: p["id"] },
            remote_image: {  # remote image, requires JMImageCache CocoaPod
              url: "http://placekitten.com/200/300",
              placeholder: "140.jpg", # NOTE: this is required!
              size: 50,
              radius: 15,
              content_mode: :scale_aspect_fill
            }
          }
        end
      }]
    end

When running `rake`:

    imageForURL:completionBlock:' type `v@:@@?' not precompiled

Seems related to this: https://github.com/jakemarsh/JMImageCache/issues/26

As this is in the v2 docs, how do you get it to work?

**Comment by jamonholmgren** [comment]
@chrise86 Is this one still an issue?

**Comment by chrise86** [comment]
@jamonholmgren it was still causing a problem for me recently, however, for some reason I believe it was linked to something else (another gem/pod possibly).

Closing for now, if I come across it again I'll dig more into it :)

**Comment by jamonholmgren** [comment]
:+1: Thanks @chrise86 !
