### ISSUE TITLE
Searchable in a web server

### ISSUE THREAD

**Issue by Ligator** [clearsightstudio/ProMotion#575]
I would like to use the ProMotion SearchBar to search items in a web server too (and populate the table). How can I do that?

If we had a callback every time that a letter is typed in Search field, then we could modify the table_data in order to add items obtained from a querying in a web server. This is just an idea, I'm open to suggestions.

I found a callback for UISearchBarDelegate called [searchBar(searchBar, textDidChange:searchText)](http://www.rubymotion.com/developer-center/api/UISearchBarDelegate.html#searchBar%3AtextDidChange%3A-instance_method) but I don't know how to use it with ProMotion.

The result might look like this:
![ios simulator screen shot 28 11 2014 14 08 14](https://cloud.githubusercontent.com/assets/3155325/5231934/076946e8-7708-11e4-80c4-8abe188544c2.png)

**Comment by jamonholmgren** [comment]
@Ligator I'm going to close this, but feel free to update if you need help or whatever. :)

**Comment by TheKidCoder** [comment]
I was able to implement a pretty naive remote search in only a few minutes.
I would be interested in getting a pull request together for this, just wanted to know if any progress had been made or anyone had any input before I get started on a PR.

**Comment by jamonholmgren** [comment]
Go for it @TheKidCoder !
