### ISSUE TITLE
PM::TableScreen title_view doesn't support passing an instantiated view

### ISSUE THREAD

**Issue by jsierles** [clearsightstudio/ProMotion#591]
Currently, you can only pass a class that responds_to #new. Here's an example of how I'm styling a custom section header view with RMQ before passing it:

```
title_view: rmq.create!(RoutineView, :routine_view)
```

I haven't submitted a PR because I may be missing an obvious way to do this today.

**Comment by jamonholmgren** [comment]
Thanks for reporting, @jsierles! You're totally right, this is a bug.

Here's the offending line of code:

https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/table/table.rb#L283

That line needs to say:

```ruby
view = section[:title_view]
```

...not `nil`.

Our specs are obviously inadequate here. You might add something to this:

https://github.com/clearsightstudio/ProMotion/blob/master/spec/unit/tables/table_module_spec.rb#L181-L184

We're only testing `viewForHeaderInSection:` 4, but 5 has the instantiated view, so we should also test that.

Looking forward to your PR. Thanks!

**Comment by jsierles** [comment]
Cool, working on that now.
