### ISSUE TITLE
Does Promotion have selectable rows in table view?

### ISSUE THREAD

**Issue by elzggr** [clearsightstudio/ProMotion#597]
Hi guys!

I've been learning Promotion for a few days now and I have yet to figure out how to create a table view in which I can select the data from multiple rows and hitting some kind of submit button to send the selected rows' data back to my rails app.

Thanks in advance.

**Comment by jamonholmgren** [comment]
Hi @elzggr,

Good question. Some of this is going to be manual, but we do provide some cool features to help you.

[Here's an example.](https://gist.github.com/jamonholmgren/379e19ccd98b41c02570) I wrote it up on my lunch break and didn't actually test it, so there are probably typos/bugs, but it'll give you the general idea.

**Comment by elzggr** [comment]
@jamonholmgren a bit of customizing and your example solution worked for me!

Thanks.

**Comment by jamonholmgren** [comment]
Great! Glad it helped. Good luck with your app. :)
