### ISSUE TITLE
Getting 'uninitialized constant PM (NameError)', but ProMotion:: works fine?

### ISSUE THREAD

**Issue by matthewsinclair** [clearsightstudio/ProMotion#612]
I've just upgraded everything to the latest gems for ProMotion and I'm noticing that the `::PM` short-cut (which I think is defined [here](https://github.com/clearsightstudio/ProMotion/blob/05490a42042d28808aebefb7f5e77bfe72412b6b/lib/ProMotion/pro_motion.rb#L3)) is not defined by the time the app runs.

This is odd, because `::ProMotion` _is_ defined, and works as expected.

`Rakefile` looks like this:
```
# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'motion/project/template/gem/gem_tasks'

require 'bundler'
require 'bundler/gem_tasks'

begin
  if ARGV.join(' ') =~ /spec/
    Bundler.require :default, :spec
  else
    Bundler.require
  end
rescue Exception => e
  puts "Exception processing Bundler.require:"
  puts e
end

require 'ib'
require 'cdq'
require 'rubygems'
require 'motion-cocoapods'
require 'bubble-wrap'
require 'bubble-wrap/all'
require 'sugarcube-all'
require 'ProMotion'
require 'motion-layout'
require 'motion-kit'
require 'motion-kit-events'
require 'restikle'
require 'tillless-uikit'

Motion::Project::App.setup do |app|
  app.name                 = 'T-UIKit'
  app.identifier           = '...'
  app.codesign_certificate = '...'
  app.provisioning_profile = 'provisioning/iOS_Team_Provisioning_Profile_.mobileprovision'

  app.frameworks += [
    'AddressBook',
    'AddressBookUI',
    'AudioToolbox',
    'AVFoundation',
    'CoreMedia',
    'CoreVideo',
    'CoreLocation',
    'CoreBluetooth',
    'QuartzCore',
    'CoreData',
    'MessageUI',
    'MobileCoreServices',
    'OpenGLES',
    'Security',
    'UIKit',
    'SystemConfiguration'
  ]
  app.detect_dependencies    = true
  app.interface_orientations = [:portrait]

  if ARGV.include? 'spec'
    app.name = 'T-UIKit Spec'
  end

  app.pods do
    pod 'AFNetworking', '~> 1.3.4'
    pod 'RestKit'
    pod 'NSData+MD5Digest'
    pod 'NSData+Base64'
    pod 'SVProgressHUD'
    pod 'JMImageCache'
    pod 'SVProgressHUD'
    pod 'TSMessages'
    pod 'ABPadLockScreen'
  end
end
```

Any ideas?

**Comment by matthewsinclair** [comment]
Hmm ... and it's worse than I thought. Changing  `PM`  to `ProMotion` in the `app_delegate.rb` is fine, but as soon as I go to use any other ProMotion classes, they're all using the `PM::` shorthand, at which point the app crashes. This is only a very, very simple app with a couple of skeleton screens in it, so I'm quite confused as to why this is happening ...

**Comment by squidpunch** [comment]
Just throwing it out there did you try `rake clean:all` ? From time to time I have noticed that's required after a gem update.

**Comment by matthewsinclair** [comment]
Yeah, always a good tip. Sadly, not helping, I'm afraid.

**Comment by matthewsinclair** [comment]
Yep, it was purely build order. An updated version of my `lib/gem_name.rb` file fixed it. Very odd, because I've been using that format for a while. I think the problem might have been that have split the gem into `lib` and `motion` components. I must have been incorrectly including them two parts somehow. 

Anyway, fixed now.

**Comment by squidpunch** [comment]
heh I was having a hard time recreating it - glad you sorted it out!

**Comment by jamonholmgren** [comment]
These load path/load order issues have been some of the more annoying and persistent ones on ProMotion. Thought I fixed it with 2.2 with the manually specified file dependencies. Perhaps I should add one for `pro_motion.rb`.

**Comment by matthewsinclair** [comment]
I've never been a fan of those manual dependencies, they always seem like such a hack ...

**Comment by jamonholmgren** [comment]
Me either! But it's the only way some gems will play well with ProMotion. :-/

**Comment by amirrajan** [comment]
Work around incase anyone stumbles over this:

```ruby
  (inside of Rakefile.rb)
  puts app.ordered_build_files

  files = [whatever build order you want]

  files.each do |f|
    app.ordered_build_files.delete(f)
  end

  files.each do |f|
    app.ordered_build_files << f
  end
```

**Comment by jamonholmgren** [comment]
Not bad!
