### ISSUE TITLE
PM::Screen and TabBarItem icons: can they be SVG, and why don't they display until after they are pressed?

### ISSUE THREAD

**Issue by matthewsinclair** [clearsightstudio/ProMotion#613]
I have a very simple app with a tab that has 5 tab bar items in it. I have two questions: 

1. Is it possible to use SVG images as the icons?
2. Why is it that the icons for each tab bar do not become visible until the first time they are touched?

Here's the controller code that establishes the tabs:
```
    class HomeScreen < PM::Screem
      title "Tab Bar"

      def on_load
        @featured_screen = FeaturedScreen.new(nav_bar: true)
        @shop_screen =     ShopScreen.new(nav_bar: true)
        @bag_screen =      BagScreen.new(nav_bar: true)
        @stores_screen =   StoresScreen.new(nav_bar: true)
        @account_screen =  AccountScreen.new(nav_bar: true)
        open_tab_bar @featured_screen, @shop_screen, @bag_screen, @stores_screen, @account_screen
      end

      # def on_appear
      #   [ 'Featured', 'Shop', 'Bag', 'Stores', 'Account', 'Featured' ].each {|s| open_tab s }
      # end

    end
```

Each screen is just an empty `PM::Screen` with a tab item specification like this:
```
    class FeaturedScreen < PM::Screen
      title "Featured"

      def on_load
        set_tab_bar_item title: 'Featured', item: 'icons/featured'
      end

    end
```
I even tried to manually select the tabs (see `on_appear`) but that makes no difference. 

When the app runs, it looks like this when it first displays:
![screen shot 2015-01-28 at 1 50 16 am](https://cloud.githubusercontent.com/assets/311495/5920325/0591d2a6-a690-11e4-97a4-8711ef70504c.png)

And then if I tap on each tab bar item, it looks like this:
![screen shot 2015-01-28 at 1 51 04 am](https://cloud.githubusercontent.com/assets/311495/5920353/219652ce-a690-11e4-907b-fcf055839d17.png)

I'm not doing anything special or out of the ordinary. This is just plain, vanilla PM tab bar item code. Any help would be much appreciated.

**Comment by matthewsinclair** [comment]
D'Oh. RTFM. See `on_init` vs 'on_load`. My bad.

**Comment by jamonholmgren** [comment]
You know, we ran into this same issue just last week. And we wrote the Fn manual. haha

**Comment by matthewsinclair** [comment]
Haha. I'm not of a fan of those manual dependencies, they always seem like such a hack ... 

Anyway, this is how I got around it:

```
    class HomeScreen < PM::Screen
      title "Home"

      def on_init
        @featured_screen = FeaturedScreen.new(nav_bar: true)
        @shop_screen =     ShopScreen.new(nav_bar: true)
        @bag_screen =      BagScreen.new(nav_bar: true)
        @stores_screen =   StoresScreen.new(nav_bar: true)
        @account_screen =  AccountScreen.new(nav_bar: true)
      end

      def on_load
        open_tab_bar @featured_screen, @shop_screen, @bag_screen, @stores_screen, @account_screen
        [ 'Account', 'Stores', 'Bag', 'Shop', 'Featured' ].each {|s| open_tab s }
      end

    end
```

**Comment by matthewsinclair** [comment]
Oh, btw: any ideas on the best way to use SVGs as tab bar item icons?

**Comment by jamonholmgren** [comment]
I've never tried! If you figure out a way, would you want to contribute? That would be awesome.

Also, wouldn't just putting each individual screen's `set_tab_bar_item` in `on_init` work better than cycling through all of them? You could also use the class method, if you want.

```ruby
    class FeaturedScreen < PM::Screen
      title "Featured"
      tab_bar_item title: "Featured", item: "icons/featured"
    end
```

**Comment by matthewsinclair** [comment]
Good point. And re: SVG, yep, I’ll try to. I found a lib that handles them, but I couldn’t get them to display in a tab bar. Still working on it ...=

**Comment by jamonholmgren** [comment]
Awesome.
