### ISSUE TITLE
Question: is it possible with a PM::GroupedTableScreen to initially position the search bar under the nav bar?

### ISSUE THREAD

**Issue by matthewsinclair** [clearsightstudio/ProMotion#616]
I am using a `PM::GroupedTableScreen` and I want to make it `searchable`, but I want the search bar to *start* under the nav bar, rather than sit between the top row of the table and the nav bar. 

By default, the search bar comes up like this:

![screen shot 2015-01-29 at 3 24 31 pm](https://cloud.githubusercontent.com/assets/311495/5952449/2a040be0-a7cb-11e4-9a6e-d471b95a5445.png)

But I'd prefer it to start out like this:

![screen shot 2015-01-29 at 3 24 37 pm](https://cloud.githubusercontent.com/assets/311495/5952453/3563bdb4-a7cb-11e4-8881-73108a3f8160.png)

And then after dragging down, it would operate as though it had started in the first position. 

You see this kind of behaviour a lot in the Apple in-built apps. My problem is that I don't really know where to look to work out how to do that. What things should should I be tweaking or fiddling with to change the position of the search bar relative to the nav bar?

Thanks,
M@

**Comment by jamonholmgren** [comment]
Will spin one up and see if I can figure it out.

**Comment by matthewsinclair** [comment]
Awesome thanks. I'm porting Tillless (generation 4) over to all of the new PM stuff. I love PM so much. :()

**Comment by jamonholmgren** [comment]
![reactiongif](http://www.reactiongifs.com/wp-content/uploads/2013/01/bashful.gif)

That's too kind. :-D It's pretty awesome to see what people are making, in part helped by PM!

**Comment by jamonholmgren** [comment]
Got it!

```ruby
class HelpScreen < PM::TableScreen
  title "Help"
  searchable

  def will_appear
    self.tableView.contentOffset = CGPointMake(0.0, self.searchDisplayController.searchBar.frame.size.height)
  end

  def table_data
    [{
      title: "About",
      cells: [{
        title: "About app",
        action: :about
      }, {
        title: "More about app",
        action: :more_about
      }]
    }, {
      title: "Help",
      cells: [{
        title: "Help me",
        action: :help
      }]
    }]
  end
end
```

Video: http://clrsight.co/jh/2015-01-28-qzz1n_0_edited.mp4

Seems like it works pretty well. Helped in part by [this](http://stackoverflow.com/a/7291090/204044) and [this](http://stackoverflow.com/a/4520812/204044).

**Comment by jamonholmgren** [comment]
Wait, that's not a GroupedTableScreen. Testing...

**Comment by matthewsinclair** [comment]
Legend! Just tested it at my end, and works a treat. Thanks mate!

**Comment by jamonholmgren** [comment]
Sweet! Maybe that should be in the API:

```ruby
class HelpScreen < PM::TableScreen
  title "Help"
  searchable placeholder: "Search items", hide_initially: true
```

(or something)

**Comment by matthewsinclair** [comment]
Yep, that would be nice. :)

**Comment by ryanlntn** [comment]
Sounds good! :+1:
