### ISSUE TITLE
open_modal from a screen in a TabBar causes problems

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion#619]
When calling `open_modal SomeScreen.new(nav_bar:true)` from a PM::Screen that's a tab bar controller, you get the following error message:

```
Presenting view controllers on detached view controllers is discouraged <SomeScreen: 0x118501c30>.
```

It works, but ideally, PM shouldn't throw messages like this.

**Comment by jamonholmgren** [comment]
I wonder if it's trying to present `SomeScreen` on some other screen.

**Comment by markrickert** [comment]
Nevermind. this was my own code issue. Sorry.

**Comment by jamonholmgren** [comment]
![mistakes](http://media.giphy.com/media/Iml0V0kAP3HQA/giphy.gif)

**Comment by GantMan** [comment]
holy hell that's funny.
