### ISSUE TITLE
turning off status_bar doesn't seem to work

### ISSUE THREAD

**Issue by malkomalko** [clearsightstudio/ProMotion#621]
Adding the familiar to your Rakefile does not work with Promotion.  Spinning up a fresh app and adding those two lines does the trick, but I'm pulling out my hair figuring out how to get this puppy off for the game I'm developing.  Any ideas?

```ruby
# hide status bar
app.info_plist['UIStatusBarHidden'] = true
app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false
```

**Comment by jamonholmgren** [comment]
Dang, sorry about that @malkomalko. I'm tied up today but maybe someone else could take a look.

**Comment by kevinvangelder** [comment]
@malkomalko Thanks for using ProMotion.

Theoretically, you should be able to do `status_bar false` in your AppDelegate, but unfortunately while testing this I discovered that Apple has changed their API (without updating their docs). I started working on an update to match this but it's too large for me to fix today. 

For now, to do this manually yourself, it looks like you need to set `preferStatusBarHidden` in your view controller. http://stackoverflow.com/questions/18934565/ios-7-hide-status-bar-on-a-child-view-controller

I hope this helps.

**Comment by kevinvangelder** [comment]
If you want to take a look at my progress, take a look at this branch. https://github.com/clearsightstudio/ProMotion/tree/bugfix/status-bar

**Comment by malkomalko** [comment]
That does not work for me.  It looks like just the inclusion of subclassing PM::Delegate ensures that the status bar will never go away no mater what technique I'm using, including the prefersStatusBarHidden.  I'll keep taking a look.

**Comment by malkomalko** [comment]
Ahh.. if I remove the UIViewControllerBasedStatusBarAppearance line from my Rakefile, prefersStatusBarHidden seems to take effect.  This is good enough for now.

**Comment by kevinvangelder** [comment]
@malkomalko Yes, there is a bug in the current version of PM::Delegate that will always show the status bar (in Ruby, `false ||= true` will always return true).

https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/delegate/delegate_module.rb#L99-L103
