### ISSUE TITLE
Searchbar being pushed to top on childview

### ISSUE THREAD

**Issue by shinnyx** [clearsightstudio/ProMotion#624]
Hi there,

I have this table screen with searchable and added as a child view controller in home_screen. When I'm searching, the search bar is being pushed to the top and it's hidden under the nav_bar in home_screen.

It is a bug or is there any workaround I could work on it? Thanks!

![ios simulator screen shot 11 feb 2015 3 47 02 pm](https://cloud.githubusercontent.com/assets/1018860/6143549/b0bb0d0c-b205-11e4-8601-f1975022fd1e.png)
![ios simulator screen shot 11 feb 2015 3 47 04 pm](https://cloud.githubusercontent.com/assets/1018860/6143550/b0bba136-b205-11e4-92e3-247a375b1dae.png)

**Comment by jamonholmgren** [comment]
Hm, could be a bug. Could you post some minimal code so I can spin something up and look?

**Comment by shinnyx** [comment]
```ruby
# home_screen.rb
class HomeScreen < PM::Screen
  def on_load
    @layout = HomeLayout.new(root: self.view)
    @layout.conversations_view = conversations_screen.view
    @layout.build
  end

  private

  def conversations_screen
    @conversations_screen ||= begin
      c = ConversationsScreen.new
      self.addChildViewController(c)
      c.parent_screen = self
      c
    end
  end
end

# home_layout.rb
class HomeLayout < MK::Layout
  view :conversations_view

  def layout
    root :main do
      add conversations_view, :conversations_view
    end
  end

  def conversations_view_style
    constraints do
      top_left x: 0, y: 0
      right "100%"
      bottom 0
    end
  end

end
```

**Comment by jamonholmgren** [comment]
@shinnyx, will get to this soon.

**Comment by jamonholmgren** [comment]
@shinnyx Sorry, completely spaced this. :-/ Did you figure something out on this? @kevinvangelder and I are looking at it now.

**Comment by jamonholmgren** [comment]
Figured it out. It's the same issue as #521. Just add this to your searching table view:

```ruby
  def will_begin_search
    self.navigationController.setNavigationBarHidden(true, animated:true)
  end

  def will_end_search
    self.navigationController.setNavigationBarHidden(false, animated:true)
  end
```

@kevinvangelder is adding this to our `PM::TableScreen` so you won't have to add the above as a workaround in future versions of ProMotion.

**Comment by shinnyx** [comment]
Thanks! @jamonholmgren @kevinvangelder

One thing with this fix is, when tapping into one of the search results, it will open a subview without triggering the `will_end_search` action and it stuck inside the subview without a nav_bar.

**Comment by shinnyx** [comment]
A small hack is to call `self.searchDisplayController.active = false` when I tap on a row.

**Comment by jamonholmgren** [comment]
Good to know! @kevinvangelder , maybe we should hold off on merging your PR until we've figured out all the edge cases.
