### ISSUE TITLE
Chat Type Screen using promotion

### ISSUE THREAD

**Issue by elzggr** [clearsightstudio/ProMotion#626]
Hi guys!

Nearly done building my first Rubymotion app :+1: :+1:  and I have 2 questions.

1) What is the best way of implementing a chat type screen using promotion? And would anyone have a gist of this perhaps?
Currently I use a table screen in which I load messages, however it doesn't look very nice to have this in a table -__-

2) IF no other option currently exists (pls pls pls tell me there is :)  ),
- how may I place a fixed label at the bottom of my table screen in which to type and send messages from? 
- how can I make the table focus on the bottom (which is where the last message appears) instead of the top which is the default...

Thanks in advance!

**Comment by elzggr** [comment]
![screen shot 2015-02-17 at 3 44 00 am](https://cloud.githubusercontent.com/assets/7364116/6225383/639f5cde-b657-11e4-8ace-81414a85c234.png)

current not so pretty view and top to bottom insteado

**Comment by jamonholmgren** [comment]
Hey @elzggr !

These things are all possible, for sure! There are some other ways you can approach this. For example, we built a chat screen in MotionKit using UILabels inside a UIScrollView, using entirely constraints. The chat input was at the bottom. It's in a closed source app, unfortunately, so I can't show you the code.

But the table view like you have above should work fine. You'll want to subclass the PM::TableViewCell and make your own to make it pretty. And you'll probably want to remove the horizontal separator view -- there are a few ways to do that, just look it up in the Apple docs.

I think this question is a bit beyond the scope of what we can answer in a Github issue, though. :-/ I do offer coaching services if you have a budget on the project to work with. Just email me at jamon@clearsightstudio.com if you're interested.

I'll leave this question open for a while to see if anyone else has more specific help. Good luck with it!

**Comment by markrickert** [comment]
I've implemented this cocoa pod in Promotion apps multiple times with great success: https://github.com/jessesquires/JSQMessagesViewController

**Comment by jamonholmgren** [comment]
^^ Wish I'd asked Mark before building my custom one in the last app. O_o

**Comment by elzggr** [comment]
@jamonholmgren thanks , and yes I figured it might beyond scope :-/ and I might take you up on the coaching services!
@markrickert wow, that's looks pretty awesome.

Thanks for the help guys.

**Comment by elzggr** [comment]
@markrickert would you be able to link me any example of implementing this with RubyMotion? I had found one but it seems the link there no longer exists and I can't seem to find any other one.

Thank you.

**Comment by markrickert** [comment]
All my implementations are closed source (client work). I'd take a look at the [`DemoMessagesViewController.m`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesDemo/DemoMessagesViewController.m) file in the project and convert it over to rubymotion. there's a LOT of customizability you can do and a single example implementation won't do it justice.

Also, if you don't already have it installed, this sublime text extension will save you hours of work - https://github.com/kyamaguchi/SublimeObjC2RubyMotion

**Comment by markrickert** [comment]
You might also want to look at this project: https://github.com/slackhq/SlackTextViewController

**Comment by elzggr** [comment]
@markrickert really can't thank you guys enough!

**Comment by jamonholmgren** [comment]
Thanks for using ProMotion, @elzggr! You can pay it forward when you get comfortable enough in RubyMotion to come back and help us maintain this thing. :) Subscribing to issues/PRs by "watching" ProMotion is a great way to stay in touch with what's happening, and once in a while you can help answer a question that we haven't gotten to yet (or even if we have). We love it when people do that.

**Comment by elzggr** [comment]
@jamonholmgren sure will!
