### ISSUE TITLE
Idea: resign_responders method in screen module

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion#632]
I often find myself wanting to resign the active keyboard responder and thought it would be nice to have a quick method in screenmodule that allows me to do this without having to remember the weird line of code: 

```ruby
self.view.endEditing(true)
```

```obj-c
[self.view endEditing:YES];
```

Thoughts on adding this to screenmodule?

```ruby
def resign_responders
  self.view.endEditing(true)
end
```

**Comment by jamonholmgren** [comment]
:+1: but in the PM::Support module and with an alias of `hide_keyboard`. :)

**Comment by jamonholmgren** [comment]
If it's in `PM::Support` it'll need to be a little smarter about what view is active, though.

**Comment by GantMan** [comment]
I like it!

**Comment by twerth** [comment]
+1

**Comment by jamonholmgren** [comment]
On second thought, this seems like an RMQ thing. What do you think. @twerth ?

**Comment by GantMan** [comment]
what would the API be?

`rmq.app.hide_keyboard`?   RedPotion `app.hide_keyboard`

my $0.02
not a huge fan of `resign_responders` over `end_editing`

Would be an easy add to RMQ.

**Comment by twerth** [comment]
Yes, `rmq.app.hide_keyboard`.

**Comment by jamonholmgren** [comment]
:+1: https://github.com/infinitered/rmq/issues/233

**Comment by GantMan** [comment]
https://github.com/infinitered/rmq/issues/233
