### ISSUE TITLE
Question regarding issue 446

### ISSUE THREAD

**Issue by majochoc** [clearsightstudio/ProMotion#634]
Its not clear from the thread. The issue was when the detail view was closed the listing view did not autorotate to landscape, correct? I'm seeing this in my project. Should my root landscape screen autorotate to landscape when a modal is closed?

I downloaded the sample project: https://github.com/jamonholmgren/pm_issue_446. This exhibits the same behavior in the simulator as I see in my own project. The listing view, does not rotate back to landscape when you close the modal.

**Comment by jamonholmgren** [comment]
@majochoc Would you mind posting a screen capture of this behavior so I can understand what's happening a little better?

ref #446

**Comment by majochoc** [comment]
When I start the app:
![whenstarted](https://cloud.githubusercontent.com/assets/95095/6403190/8c3cb96c-bddb-11e4-8b39-fe2f90245fd6.png)

When I open the details:
![opendetails](https://cloud.githubusercontent.com/assets/95095/6403189/8c3bdeac-bddb-11e4-8ff1-1c8da9f6ecf7.png)

When I close the details:
![closedetails](https://cloud.githubusercontent.com/assets/95095/6403188/8c351ad6-bddb-11e4-9fc6-7e289db29255.png)

Should I expect the landscape screen to rotate back to landscape? For a screen that supports only landscape orientation you end up with the middle portion of the landscape screen positioned to the top of a portrait orientation. Leaving the whole bottom half of the screen blank. It rotates when a device is rotated, but behavior is a bit weird especially if you have a LandscapeRight screen. I can send you an example of my screen, but need to obfuscate it for NDA

**Comment by jamonholmgren** [comment]
Got it! Will look into it soon.

**Comment by jamonholmgren** [comment]
@majochoc 

What are the values of:

```ruby
# Rakefile
app.interface_orientations = [ ?? ]
```

And both screen `supportedInterfaceOrientations` and `preferredInterfaceOrientationForPresentation` methods?

**Comment by majochoc** [comment]
The above screen shots are from your sample repository for pm_issue_446 untouched.
So:
app.interface_orientation not set
def supportedInterfaceOrientations
  UIInterfaceOrientationMaskLandscape
end
def preferredInterfaceOrientationForPresentation 
  UIInterfaceOrientationLandscapeLeft
end

I mirror these settings in my own app, except I have LandscapeRight instead of Left.

I added app.interface_orientations = [:portrait, :landscape_right] to my rakefile, but the behavior did not change.

**Comment by jamonholmgren** [comment]
I was able to reproduce it: http://clrsight.co/jh/2015-02-27-q5kuy_0_edited.mp4

It looks like this isn't really a ProMotion bug -- other people are reporting it:

http://stackoverflow.com/questions/25391564/ios-7-dismiss-modal-view-controller-and-force-portrait-orientation

We're forwarding rotation requests to the visible view controller, which is the modal. If you override the methods like the second answer recommends, it hopefully will work as a workaround.

I'm not sure what to do within ProMotion to work around this behavior -- seems fairly specific to the use case. Any ideas, @majochoc ?

**Comment by majochoc** [comment]
No good ideas. For now I'm going to avoid the issue and keep my screens portrait.

**Comment by jamonholmgren** [comment]
Gotcha. Let me know if you think of anything later on. Thanks for using ProMotion. :)
