### ISSUE TITLE
How to determine what field to index on?

### ISSUE THREAD

**Issue by cbetta** [clearsightstudio/ProMotion#642]
I understand that `table_data_index` allows me to determine what letters are show in the index, but how do I determine what index a field has? I dont use the default title property.

**Comment by jamonholmgren** [comment]
@cbetta I usually just assign letters to table sections and use those. Something like:

```ruby
@my_cell_data.map{|c| c[:my_title_attribute][0]}.uniq.sort # => [ "B", "F", "G", "I", "Q" ]
```

Make sure to actually provide those table sections in your `table_data` method, rather than dumping them all into one section. Cocoa Touch will expect to jump to a section with that letter as a title.

**Comment by cbetta** [comment]
ah, so I should use sections in my tabe_data? Got an example of that?

**Comment by markrickert** [comment]
https://github.com/clearsightstudio/ProMotion/blob/eaa02d023389454e54e40c3113e1febd50240bd3/lib/ProMotion/table/extensions/indexable.rb#L7

It will automatically get the first letter of all the section titles if you don't use the `table_data_index` method :)

Just set `indexable` and then set the section titles and BAM! You're done!

**Comment by markrickert** [comment]
Example here: https://github.com/clearsightstudio/ProMotion/blob/master/app/test_screens/table_screen_indexable.rb

**Comment by cbetta** [comment]
Ah, so that's what I missed. I didnt add my code in sections. Tnx!

**Comment by markrickert** [comment]
:+1: Glad we could help!

**Comment by cbetta** [comment]
:heart: to ProMotion :)
