### ISSUE TITLE
Setting status_bar does nothing

### ISSUE THREAD

**Issue by cbetta** [clearsightstudio/ProMotion#644]
```ruby
status_bar :light
```

I tried every way possible on iOS8 to get that line to do something but the only want to change the status bar color seems to just use old fashioned:

```ruby
  def preferredStatusBarStyle
    UIStatusBarStyleLightContent
  end
```

Am I missing something?

**Comment by cbetta** [comment]
Ended up making it work by adding 

```ruby
  app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false
```

to my Rakefile

**Comment by jamonholmgren** [comment]
There is a fix for this coming, but thanks for reporting anyway!
