### ISSUE TITLE
WebScreen causing NSURLErrorDomain error -999 when navigating to a different page before current page finishes loading

### ISSUE THREAD

**Issue by ronyv89** [clearsightstudio/ProMotion#646]
I have a WebScreen in my application, for doing Oauth2 authentication for Uber. I successfully load the login page for  uber. But if I click on 'Login with Facebook' button, before the page is loaded completely it throws 'NSURLErrorDomain error -999'. Can this be overcome?

**Comment by jamonholmgren** [comment]
Could you post the code? (you can omit proprietary stuff)

**Comment by ronyv89** [comment]
class UberLoginScreen < PM::WebScreen
  title "Login with Uber"
  def content
    
    NSURL.URLWithString("https://login.uber.com/oauth/authorize?client_id=xxxxxxxxx&redirect_uri=xxxxxxxxxxxx&response_type=token")
  end

  def load_started
  end

  def load_finished
    app = UIApplication.sharedApplication
    delegate = app.delegate
    location = webview.request.URL.absoluteString
    if location.hasPrefix("http://xxxxxxx/callback")
      afterAccessToken = location.componentsSeparatedByString("#access_token=").last
      accessToken = afterAccessToken.componentsSeparatedByString("&token_type").first
      delegate.open ProfileScreen.new(nav_bar: true, access_token: accessToken)
    else
      
    end
  end

  def load_failed(error)
    if error.code == NSURLErrorCancelled
      puts webview.request
    end
  end


end

**Comment by jamonholmgren** [comment]
Any ideas, @markrickert ?

**Comment by ronyv89** [comment]
Any update on this?

**Comment by ronyv89** [comment]
Never mind. Found a hacky workaround, by disabling user interaction on load_started and enabling user interaction on load_finished

**Comment by markrickert** [comment]
Interesting. I wasn't able to get a lot of time to try and figure this out, but would you care to share the code you used to work around this issue so that others that might have the same problem in the future can benefit from it?

The workaround might also give us a clue as to what is going on behind the scenes and lead to a possible fix.

**Comment by jamonholmgren** [comment]
@ronyv89 glad you found a workaround. I worked on it for about 30 minutes when you first reported it, trying to replicate, but couldn't.

**Comment by ronyv89** [comment]
The workaround was a custom one, which counts the number of pages loaded, and disables the user interaction till it reaches the final page.

**Comment by markrickert** [comment]
Interesting. Care to share any code here for those who might have the same problem in the future?
