### ISSUE TITLE
superclass mismatch for class AppDelegate (TypeError) 2

### ISSUE THREAD

**Issue by zxiest** [clearsightstudio/ProMotion#661]
Hello =)

Has anyone seen a similar error upon running the app in the simulator?

2015-04-02 02:53:59.309 SomeApp[9166:4540704] superclass mismatch for class AppDelegate (TypeError)
2015-04-02 02:53:59.312 SomeApp[9166:4540704] *** Terminating app due to uncaught exception 'TypeError', reason: 'superclass mismatch for class AppDelegate (TypeError)

The code in app/app_delegate.rb is the following:

    class AppDelegate < PM::Delegate
       def on_load(app, options)
           open LoginScreen.new(nav_bar: false)
      end
    end

**Comment by jamonholmgren** [comment]
I usually see this if I've already defined `AppDelegate` somewhere else, and this re-opens the class. Adding a new superclass isn't allowed in that case.

**Comment by zxiest** [comment]
This is what I was exactly looking for but I had forgotten a gem that extends AppDelegate too. Removing the gem from my Gemfile fixed the issue =) Thanks for your time!

**Comment by jamonholmgren** [comment]
Sweet!
