### ISSUE TITLE
Deprecate `PM::Logger` in favor of motion_print

### ISSUE THREAD

**Issue by jamonholmgren** [clearsightstudio/ProMotion#665]
I'd like to deprecate `PM::Logger` in favor of the much better [motion_print](https://github.com/OTGApps/motion_print) by our very own @markrickert. We do use informational output in various spots in ProMotion, so I think specifying it as a dependency (development and runtime) is reasonable.

Thoughts?

**Comment by GantMan** [comment]
Love motion print.   One thing I like is that you can put smart object printing in `mp` and have it understand and create super-useful output.

**Comment by ryanlntn** [comment]
:+1:

**Comment by squidpunch** [comment]
:+1: 

could probably put it in place, delegate any current use of it of an existing app to use `mp` and give a deprecation warning, and remove it completely in a later release

**Comment by jamonholmgren** [comment]
:+1: to @squidpunch's idea.

Also, it would be cool if it were simple to colorize random strings.

```ruby
mp "This method fired", color: :red
```

That would allow me to port over `PM.logger.warn` and whatnot, easier.

**Comment by markrickert** [comment]
Ask and ye shall receive! :+1: 

Can you test this feature out a bit for me before I push a new gem version?

https://github.com/OTGApps/motion_print#fancy-debugging-tips

```ruby
mp "My String", force_color: :blue # This is usually yellow
```

works with all object types.

**Comment by jamonholmgren** [comment]
:+1: Looks great! We'll give it a go on our latest projects.

@kevinvangelder, @carlinisaacson, @yulianglukhenko, maybe try this out on your respective projects?

**Comment by squidpunch** [comment]
@jamonholmgren as a end result, do we envision removing the `PM.logger` completely and leaving it up to the users to use `mp blah` themselves as well as in our base here - or do we want some sort of "happy path wrapper" that we can use easily internally to send output in the various places that `PM.logger` is used already here in PM.

I have quick commit that adds the warning for deprecation and adds the dependency - but I would like to update the current places we use `PM.logger` in that same commit as to not include deprecation warnings from our own code :smile: 

Depending on your final vision, will depend on the next steps before I consider this "PR Ready"

**Comment by jamonholmgren** [comment]
I don't think anybody really uses `PM.logger` anymore, so it's fine if we deprecate it. And yes, let's update those places with `mp`. :) Let's keep the various colors, though.

**Comment by squidpunch** [comment]
Sounds good. I'll push something up for review soon!
