### ISSUE TITLE
Global status_bar option?

### ISSUE THREAD

**Issue by dmarkow** [clearsightstudio/ProMotion#668]
Before PM 2.2.0, I was able to globally set a "light" status bar by including this in my `Rakefile`:

```ruby
app.info_plist['UIViewControllerBasedStatusBarAppearance'] = false
app.info_plist["UIStatusBarStyle"] = "UIStatusBarStyleLightContent"
```

However, the new `status_bar` setting on screens overrides this. If I don't provide a `status_bar :light` setting on any given screen, the `resolve_status_bar` method will override my Rakefile settings and use `UIStatusBarStyleDefault` (black) instead. 

Is there a way around having to add `status_bar :light` to my 50+ separate screens? I can work on a PR to add a global setting or to respect what's in the Rakefile or something, but I just wanted to make sure I wasn't missing something first.

**Comment by jamonholmgren** [comment]
Oh, wow. Yeah, that's an unintended consequence.

We need to respect what's in the Rakefile, I think, if no `status_bar :light` provided.

**Comment by dmarkow** [comment]
Also, what if the global setting is UIStatusBarStyleLightContent? We would need a way to set a specific screen to `UIStatusBarStyleDefault` (which might be called "dark"?). Here's a potential approach:

```ruby
case self.class.status_bar_type
when :none
  status_bar_hidden true
when :light
  status_bar_hidden false
  status_bar_style UIStatusBarStyleLightContent
when :dark
  status_bar_hidden false
  status_bar_style UIStatusBarStyleDefault
else
  status_bar_hidden
  global_style = NSBundle.mainBundle.objectForInfoDictionaryKey("UIStatusBarStyle")
  status_bar_style global_style ? Object.const_get(global_style) : UIStatusBarStyleDefault
end
```

I'm not crazy about using `const_get`, but the plist value needs to be stored as a String and status_bar_style needs to be passed the constant/integer. The only two valid non-deprecated options are already used under :light and :dark, so I don't think we would run into uninitialized constant exceptions unless someone used an invalid value in the plist.

Thoughts? If this approach seems okay, I can throw together a PR with some specs for this.

**Comment by jamonholmgren** [comment]
I'm okay with this approach!

**Comment by jamonholmgren** [comment]
:confused:
