### ISSUE TITLE
searchable hide_initially: true  - issue with tab bar controller

### ISSUE THREAD

**Issue by carlinisaacson** [clearsightstudio/ProMotion#669]
I am using the `hide_initially: true` option for `searchable` in my table views. I discovered that when I open a tab bar with a table screen (`open_tab_bar TableScreen.new(nav_bar: true)`), the search bar is only hidden halfway. If I just open a table screen (`open TableScreen.new(nav_bar: true)`) the search bar is hidden all of the way.

It appears that setting `contentOffset` on a scroll view acts funny inside a tab bar controller.

![http://clrsight.co/ci/8xgelzbfw9.png](http://clrsight.co/ci/8xgelzbfw9.png?+)

**Comment by carlinisaacson** [comment]
Upon further investigation I found that when opening the screen in the tab bar and not setting `nav_bar: true`
```ruby
open_tab_bar TableScreen
```
hide_initially appears to work fine. It seems to only malfunction when there is a nav_bar

**Comment by jamonholmgren** [comment]
@carlinisaacson You probably want to look here: https://github.com/clearsightstudio/ProMotion/blob/173b412e48e74d37c9e7b86f2abae703f5bdea25/lib/ProMotion/table/table.rb#L49-L51

**Comment by carlinisaacson** [comment]
@jamonholmgren That is how I figured out it is `contentOffset` that is behaving oddly in this situation. So why it is behaving oddly is the actual issue that needs to be resolved here I suppose.

**Comment by andersennl** [comment]
I've had the same problem with the same setup.

**Comment by andersennl** [comment]
Did you find out anything new about this? Tables look indeed a little weird with this bug.

**Comment by jamonholmgren** [comment]
I don't think we ever did. What did we do, @carlinisaacson ?

**Comment by carlinisaacson** [comment]
@jamonholmgren 
Honestly, I think it worked itself out. Not sure what the change was that fixed it. Then we switched to the custom search bar that you built in that app we shouldn't have an issue with it anymore.

**Comment by andersennl** [comment]
I've updated to the newest version yesterday and the bug is gone. Thanks a lot! :+1:

**Comment by jamonholmgren** [comment]
Great!
