### ISSUE TITLE
Tabledata not refreshed with `on_refresh` callback in `on_load` callback

### ISSUE THREAD

**Issue by poc7667** [clearsightstudio/ProMotion#673]
My tableview won't reload data , it only shows `noob` but not redreshed data.

Do I missing any steps in my code ?

```ruby
	class ReservoirsScreen < PM::TableScreen
	  title "I want to refresh"
	  refreshable
	  def on_load
	    @returned_data ||= [{title:'noob'}]
	    on_refresh
	  end
	  def table_data
	    [{
	      cells: @returned_data.map do |reservoir|
	        {
	          title: reservoir["title"],
	          action: :select_reservoir,
	          arguments: { reservoir: reservoir["title"] }
	        }
	      end
	    }]
	  end


	  def select_reservoir(reservoir)
	    PM.logger.info reservoir
	  end 

	  
	  def on_refresh
	    start_refreshing
	    get_reserviors
	    stop_refreshing
	    update_table_data          
	  end  

	  def get_reserviors
	    start_refreshing
	    url_string = "http://128.199.223.114:10080/"
	    AFMotion::JSON.get(url_string) do |result|
	      if result.success?
	        @returned_data = []
	        result.object["data"].each do |r|
	          @returned_data << {
	            title: [r["reservoirName"], r["immediatePercentage"]].join(":")
	          }
	        end
	      else
	        @returned_data = ['failed','d']
	      end
	    end 
	    stop_refreshing
	    update_table_data      
	  end

	end
```

Here my gems versions

  * ProMotion (2.3.0)
  * activesupport (4.2.1)
  * afmotion (2.5)

**Comment by jamonholmgren** [comment]
Hey @poc7667 ! You almost have it, but remember that AFMotion does asynchronous requests, so you need to put your `stop_refreshing` and `update_table_data` in the callback:

```ruby
      def on_refresh
        start_refreshing
        get_reserviors
      end  

      def get_reserviors
        start_refreshing
        url_string = "http://128.199.223.114:10080/"
        AFMotion::JSON.get(url_string) do |result|
          if result.success?
            @returned_data = []
            result.object["data"].each do |r|
              @returned_data << {
                title: [r["reservoirName"], r["immediatePercentage"]].join(":")
              }
            end
          else
            @returned_data = ['failed','d']
          end
          stop_refreshing
          update_table_data      
        end 
      end

```

**Comment by poc7667** [comment]
@jamonholmgren  But I've already put   `stop_refreshing` `update_table_data ` in the necessary code block, but it still not works, and more detailed guide, very appreciate your reply.

	  def on_refresh
	    start_refreshing
	    get_reserviors
	    update_table_data
	    stop_refreshing
	  end  

	  def get_reserviors
	    url_string = "http://128.199.223.114:10080/"
	    AFMotion::JSON.get(url_string) do |result|
	      if result.success?
	        @returned_data = []
	        result.object["data"].each do |r|
	          @returned_data << {
	            title: [r["reservoirName"], r["immediatePercentage"]].join(":")
	          }
	        end
	      else
	        @returned_data = ['failed','d']
	      end
	    end 
	  end

	  def table_data
	    [{
	      cells: @returned_data.map do |reservoir|
	        {
	          title: reservoir["title"],
	          action: :select_reservoir,
	          arguments: { reservoir: reservoir["title"] }
	        }
	      end
	    }]
	  end

**Comment by poc7667** [comment]
@jamonholmgren  Thanks for your reply, I realized it

**Comment by jamonholmgren** [comment]
:+1:
