### ISSUE TITLE
Swipe a table cell from left to right, similar to Delete

### ISSUE THREAD

**Issue by paxer** [clearsightstudio/ProMotion#682]
Hi,

Is there a way in ProMotion::TableScreen to swipe table cell from left to right and show an action buttons? Similar like with the Delete button in case when you swipe from right to left with editing_style: delete option?

Seems like there is an API in iOS8 for that? http://stackoverflow.com/a/24540538/338897

![Swipe Demo] (http://i.stack.imgur.com/GgIIo.gif)

**Comment by markrickert** [comment]
There is no api for this. I'd advise using this excellent library - https://github.com/MortimerGoro/MGSwipeTableCell

**Comment by paxer** [comment]
thanks, any tips how to use it the context of PM::TableScreen DSL?

**Comment by paxer** [comment]
ok here is the working solution, maybe will be useful for somebody:

1) In the Gemfile make sure you have
gem 'motion-cocoapods' if not follow instructions how to setup it
add to Rakefile
```
  app.pods do
    pod 'MGSwipeTableCell'
  end
```
and install it

then in your < PM::TableScreen class an example table_data method
```
  def table_data
    [{
         cells: [
             {
                 cell_class: MGSwipeTableCell,
                 title: 'Item 1',
                 subtitle: 'Subtitle 1',
                 editing_style: :delete,
                 cell_identifier: 'ItemCellIdentifier',
                 properties: {
                     leftButtons: [MGSwipeButton.buttonWithTitle('Done', backgroundColor: UIColor.greenColor)]
                 }
             }
         ]
     }]
  end
```
while "left to right" swap this will show a green button "Done" similar to "Delete"

**Comment by kevinvangelder** [comment]
@paxer Thanks for the example, I'm sure it will come in handy for other users in the future!

**Comment by markrickert** [comment]
I've been toying with writing a blog post about this very subject recently. I prefer to use a custom cell subclass and do all my button creating in the subclass.
