### ISSUE TITLE
editing_style: :delete is broken starting with v2.3.1

### ISSUE THREAD

**Issue by wallclimber21** [clearsightstudio/ProMotion#690]
Hello Promotion crew,

It looks like the editing_style: :delete option is broken in the current Promotion release (v2.3.1).

I'm simply testing it by changing the app_delegate in the main repo to use TestTableScreen instead of BasicScreen, and deletable rows just don't react at all when you swipe left.

v2.3.0 works fine when left sliding the 'Just another deletable blank work'.
v2.3.1 doesn't do anything at all.

I've isolated the issue to commit f88864f. 

It looks like the self.extend either doesn't work when running as a real app, yet the spec test seems to be fine. Weird.

Tom

**Comment by wallclimber21** [comment]
I've isolated the issue to commit f88864fe2089f6e600aa730536cfeddf4980897c.

**Comment by markrickert** [comment]
Thanks for the detective work! I'll take a look at this today.

**Comment by markrickert** [comment]
Discussion is going on on #653
