### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by zxiest** [clearsightstudio/ProMotion#692]
Hey guys =)

I'm not sure you're aware about the broken links on the images below.  This is the same case in RedPotion too.

**Comment by jamonholmgren** [comment]
Oh, thanks @zxiest ! We'll get that fixed ASAP.

**Comment by zxiest** [comment]
@jamonholmgren thanks!

**Comment by zxiest** [comment]
Hey guys, has this been merged with master?
Only "Screens" and "Grouped Tables" seem to have have been fixed... All the other links on the images are still broken =)

**Comment by markrickert** [comment]
It is in master. I'm seeing all links currently working on the master branch readme.

**Comment by zxiest** [comment]
Oh yes, working now :-) Must have been a caching issue :-) Thanks guys!

**Comment by markrickert** [comment]
:+1:

**Comment by jamonholmgren** [comment]
Thanks guys!
