### ISSUE TITLE
How could I toggle nav bar button's title when click on the button  #question

### ISSUE THREAD

**Issue by poc7667** [clearsightstudio/ProMotion#693]
How could I change the title 'sorting' into 'done' when click the 'sorting' button ?

      def on_init
        set_nav_bar_button :right, title: "Sorting", action: :toggle_sort_function
      end
     def toggle_sort_function
        toggle_edit_mode
      end

**Comment by jamonholmgren** [comment]
```ruby
  def on_init
    set_nav_bar_button :right, title: "Sorting", action: :toggle_sort_function
  end
  def toggle_sort_function
    toggle_edit_mode
    self.title = (self.title == "Sorting" ? "Done" : "Sorting")
  end
```

I typically don't like two toggles at one time (like I just posted above), because they can get out of sync if one toggles without the other. So, if you return from your `toggle_edit_mode` what the *new* mode is, it'll be more deterministic:

```ruby
  def on_init
    set_nav_bar_button :right, title: "Sorting", action: :toggle_sort_function
  end
  def toggle_sort_function
    new_mode = toggle_edit_mode
    self.title = (new_mode == :done ? "Done" : "Sorting")
  end
```

**Comment by jamonholmgren** [comment]
Or, if you want to get really fancy:

```ruby
  def on_init
    set_nav_bar_button :right, title: "Sorting", action: :toggle_sort_function
  end
  def toggle_sort_function
    toggle_edit_mode do |new_mode|
      self.title = (new_mode == :done ? "Done" : "Sorting")
    end
  end
```

**Comment by jamonholmgren** [comment]
Feel free to comment again if you need more help!
