### ISSUE TITLE
[Version 2.4.1] undefined method `mp:force_color` in logger.rb:67

### ISSUE THREAD

**Issue by seantan** [clearsightstudio/ProMotion#696]
There seems to be some error in the show_deprecation_warning added to version 2.3.1 for logging.

```
logger.rb:67:in `show_deprecation_warning': undefined method `mp:force_color:' for #<ProMotion::Lo
gger:0x10baa2490 ...> (NoMethodError)
```

**Comment by seantan** [comment]
Seems that it could be a bug with RubyMotion compiling the dependencies, when `motion_print` is not explicitly defined in the Gemfile.

I'm able to replicate this with clean compilation, i.e. `rake clean:all; rake pod:install; rake spec`. 

Without `motion_print` defined in Gemfile, throws the `mp` not found error. Debugging in the REPL shows `mp` is not available. Seems that it's not compiled in. `bundle check` shows the gem is installed.

When `motion_print` is defined in Gemfile, things work as expected, with the deprecation messages showing as expected.

**Comment by squidpunch** [comment]
> I'm able to replicate this with clean compilation, i.e. rake clean:all; rake pod:install; rake spec.

is this `rake spec` or `bundle exec rake spec` ?

not sure thats the problem specifically, but I was pretty sure I tested this on a fresh install without issue.  I'll try and replicate the problem - thanks for letting us know!

**Comment by seantan** [comment]
I was using `bundle exec rake` via a bash alias. 

When testing, do execute `bundle update` when you change the `Gemfile`. The resulting `Gemfile.lock` is different, with the explicit define in `Gemfile` adding `motion_print` under the `DEPENDENCIES` section of the `Gemfile.lock`.

**Comment by squidpunch** [comment]
thanks @seantan - I will see what I can come up soon!

**Comment by seantan** [comment]
@squidpunch thanks for looking into it so soon. :)

**Comment by squidpunch** [comment]
hey @seantan I'm having some trouble reproducing this, and it looks like the 2.3.1 release didnt include the deprecation stuff (or a motion_print dependency) https://rubygems.org/gems/ProMotion/versions/2.3.1 

maybe we're taking 2.4.1?  I think I am seeing this reproduced on 2.4.1.  workarounds are to add `require "motion_print"` to your rakefile, or as you said add it specifically to gemfile.

I know we dont have to do this kind of thing with other gems - and I believe this same config works on redpotion.

I will see what I can dig up, any ideas @markrickert ?

**Comment by seantan** [comment]
@squidpunch sorry, for the mixup in version number. Yes it's version 2.4.1 I'm referring to. As far as I can tell `motion_print` is added in 2.4.1 release.

Thanks, noted the workaround on adding a require to Rakefile.

**Comment by squidpunch** [comment]
@seantan see #698 - let us know if that works when you get a chance

**Comment by seantan** [comment]
@squidpunch Will do
