### ISSUE TITLE
How to navigate back to home screen without nav bar?

### ISSUE THREAD

**Issue by andrewhavens** [clearsightstudio/ProMotion#700]
I'm running into an issue with transitioning from one screen to another then back to the first screen. I need to create a home screen which does not have a nav bar (splash page with signup/login button). I can't seem to figure out the code I need to create the behavior I'm trying to achieve. Here's what I have so far (working with RedPotion):

```ruby
class AppDelegate < PM::Delegate
  status_bar true, animation: :fade
  def on_load(app, options)
    open HomeScreen.new(nav_bar: false)
  end
end

class HomeScreen < PM::Screen
  stylesheet HomeScreenStylesheet

  def on_load
    append(UIButton, :sign_up_button).on(:tap) do
      open CreateAccountScreen.new(nav_bar: true), animated: true
    end
    append(UILabel, :sign_in_text)
  end
end

class CreateAccountScreen < PM::Screen
  title "Create Account"
  stylesheet CreateAccountScreenStylesheet

  def on_load
    set_nav_bar_button :left, title: '<', action: :nav_left_button
    @hello_world = append!(UILabel, :hello_world)
  end

  def nav_left_button
    open_root_screen HomeScreen.new(nav_bar: false), animated: true
    # I've also tried
    # open HomeScreen
    # open HomeScreen.new(nav_bar: false), animated: true
    # close
  end
end
```

When I tap the "sign up" button, it does not slide in (just immediately displays). When I tap the back button (left nav button) it crashes the app with an error:

> Terminating app due to uncaught exception 'ArgumentError', reason: 'create_account_screen.rb:17:in `nav_left_button': wrong number of arguments (2 for 1) (ArgumentError)

What am I doing wrong?

**Comment by markrickert** [comment]
Try:

```ruby
open_root_screen HomeScreen.new(nav_bar: true, hide_nav_bar: true), animated: true
```

**Comment by markrickert** [comment]
Basically, you want to have the navigation stack from the very beginning... then unhide it in your next screen.

**Comment by andrewhavens** [comment]
Okay, so I've updated AppDelegate to

    open HomeScreen.new(nav_bar: true, hide_nav_bar: true)

and HomeScreen to

    open CreateAccountScreen.new(nav_bar: true, hide_nav_bar: false)

That seems to have fixed the animation and I didn't even need to specify `animate: true`. However, `hide_nav_bar: false` is not working as the CreateAccountScreen nav bar is still hidden. Is there a different option that I should pass?

**Comment by ryanlntn** [comment]
@andrewhavens It looks like you may just want to omit the `hide_nav_bar: false`: https://github.com/clearsightstudio/ProMotion/blob/23e7c8c490aa33d22e4524c1e0f0d4228148fb6f/lib/ProMotion/screen/nav_bar_module.rb#L64

Not sure why it's checking explicitly for `nil`.

**Comment by andrewhavens** [comment]
@ryanlntn Yeah, I tried omitting that option, but it's still hidden. It seems that I need to explicitly show it.

**Comment by ryanlntn** [comment]
@andrewhavens I was able to recreate your issue. Once nav bar is hidden it stays hidden. As a work around you could do this in `on_load`: `self.navigationController.setNavigationBarHidden(false)`.

**Comment by ryanlntn** [comment]
@jamonholmgren This appears to be due to where we're calling `setNavigationBarHidden` in the lifecycle. Moving the call to `view_will_appear` or later resolves the issue. Now I just need to find a way to cleanly.

**Comment by andrewhavens** [comment]
Thanks, that solved my first problem.

Related to this, now I'm having issues trying to navigate back to the first screen. Right now I have this:

```
def on_load
  set_nav_bar_button :left, title: '<', action: :return_to_home_screen
end

def return_to_home_screen
  # open_root_screen HomeScreen, hide_nav_bar: true, animated: true # wrong number of arguments error
  open HomeScreen, hide_nav_bar: true, animated: true # animates wrong direction, displays nav_bar
end
```

I'd like the back button to use the normal "< Back" label, but I'm not sure how to set it to that. When I leave off the `set_nav_bar_button` the label ends up `< HomeScreen`. But my home screen does not have a nav bar, so I'm not setting a title.

What should I do differently?

**Comment by ryanlntn** [comment]
@andrewhavens That sounds like a bug. @jamonholmgren ? Perhaps we should open a separate issue.

**Comment by jamonholmgren** [comment]
Yeah, sounds like a bug. Can you create a new issue Andrew?
