### ISSUE TITLE
Issue with navigating back to the first screen

### ISSUE THREAD

**Issue by andrewhavens** [clearsightstudio/ProMotion#703]
I'm having issues trying to navigate back to the first screen. Right now I have this:

```ruby
def on_load
  set_nav_bar_button :left, title: '<', action: :return_to_home_screen
end

def return_to_home_screen
  #  wrong number of arguments error
  # open_root_screen HomeScreen.new(nav_bar: true, hide_nav_bar: true), animated: true
  # open_root_screen HomeScreen, hide_nav_bar: true, animated: true
  open HomeScreen, hide_nav_bar: true, animated: true # animates wrong direction, displays nav_bar
end
```

I'd like the back button to use the normal "< Back" label, but I'm not sure how to set it to that. When I leave off the set_nav_bar_button the label ends up < HomeScreen. But my home screen does not have a nav bar, so I'm not setting a title.

What should I do differently?

**Comment by andrewhavens** [comment]
I found a way to do this but it feels wrong. If I set the title of the home screen to "Back" and don't add a left nav button, it works:

```ruby
class HomeScreen < PM::Screen
  title "Back"

  def on_load
    append(UIImageView, :background)
    append(UILabel, :sign_in_text).on(:tap) do
      open SignInScreen.new(nav_bar: true)
    end
  end
# ...
  def will_appear
    self.navigationController.setNavigationBarHidden(true)
  end
end

class SignInScreen < PM::Screen
  title ""

  def on_load
    self.navigationController.setNavigationBarHidden(false)
    set_nav_bar_button :right, title: 'Continue', action: :authenticate
  end
end
```

**Comment by jamonholmgren** [comment]
Do this:

```ruby
close to: :root
```

Should do what you want. :-)

**Comment by andrewhavens** [comment]
Yep, that worked! I think the first time I tried that, I didn't think it worked because the navigation bar was hidden, but now I have that nav bar hidden/visible issue sorted out.

So really my issue now is trying to get the left nav button to appear correctly. I can manually create a left nav button and a callback:

```ruby
def on_load
  set_nav_bar_button :left, title: '< Back', action: :return_to_home_screen
end

def return_to_home_screen
  close to: :root
end
```

...but it requires me to manually write the code (also, my title is incorrect because it's not displaying the native `<` icon). I found that when I leave off the left nav button, it behaves as intended out of the box. So I really don't need to manually add the left nav button. However, in my case, the home screen does not display a nav bar, so I shouldn't need to specify a title. However, it seems to be defaulting to the name of the class, which does not seem like a good default:

```ruby
class HomeScreen < PM::Screen
  # no title set

  def on_load
    append(UILabel, :sign_in_text).on(:tap) do
      open SignInScreen.new(nav_bar: true)
    end
  end

  def will_appear
    self.navigationController.setNavigationBarHidden(true)
  end
end

class SignInScreen < PM::Screen
  # I also don't want to display a title here, but I have to set it to a blank string in order to remove it from the nav bar
  title ""

  def on_load
    self.navigationController.setNavigationBarHidden(false)
    set_nav_bar_button :right, title: 'Continue', action: :authenticate
  end
end
```
![screen shot 2015-06-15 at 10 10 30 am](https://cloud.githubusercontent.com/assets/446392/8165626/cd7d7644-1346-11e5-9ebd-60baa6c2d62c.png)

I feel like the default should be if you don't set a title, the title is not displayed, and if you navigate down the stack, the back button should say "< Back" instead of displaying the class name.

**Comment by jamonholmgren** [comment]
I'd agree with that. Would you want to contribute a PR to ProMotion to make that happen? It seems pretty doable.

**Comment by andrewhavens** [comment]
@jamonholmgren I would be happy to! I'll try my best. =]

**Comment by jamonholmgren** [comment]
Awesome!
