### ISSUE TITLE
Implement didReceiveMemoryWarning

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion#712]
Idea from @paulsturgess' Inspect 2015 talk. Maybe we should implement something on `PM::Screen` that calls your screen's method:

```ruby
def memory_warning
  # do something here to clean up memory
end
```

I'd also say maybe we should auto-print a message to the screen when a memory warning is received and the user hasn't implemented the `memory_warning` method in their screen.

Thoughts?

**Comment by jamonholmgren** [comment]
I love it. I think `on_memory_warning` would be consistent with the API. I think we could do `mp "Received memory warning in #{self.inspect}. Implement `on_memory_warning`.", force_color: UIColor.redColor` or something. As a developer, I'd want to deal with those for sure.

I faked the output here for discussion:

![screen shot 2015-07-02 at 2 41 52 pm](https://cloud.githubusercontent.com/assets/1479215/8477177/7e67a626-20c8-11e5-9fa1-26897db100ee.png)

**Comment by squidpunch** [comment]
:+1:
