### ISSUE TITLE
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FooView superview]: unrecognized selector sent to class 0x10d5690f0'

### ISSUE THREAD

**Issue by cavalryjim** [clearsightstudio/ProMotion#718]
I am using ProMotion via RedPotion.  When creating a view via 'potion create view foo_view' and then trying to add the view to a screen, I receive the following error: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FooView superview]: unrecognized selector sent to class 0x10d5690f0'

class HomeScreen < PM::Screen
  title "home"
  stylesheet HomeScreenStylesheet
  
  def on_load
    add FooView , { frame: [[ 50, 50 ], [ 100, 100 ]]}
    ...
  end
end

class FooView < UIView
  def on_load
    apply_style :foo_view
  end
end

class HomeScreenStylesheet < ApplicationStylesheet
  include FooViewStylesheet
  ......
end

module FooViewStylesheet
  def foo_view(st)
    st.frame = {l: 5, t: 100, w: 80, h: 40}
    st.background_color = color.light_gray
    # Style overall view here
  end
end

**Comment by squidpunch** [comment]
```
def on_load
add FooView , { frame: [[ 50, 50 ], [ 100, 100 ]]}
...
end
```

is this really `add` ?  Using redpotion, I'd expect this to be something like this...

```
def on_load
  append(FooView)
end
```

**Comment by markrickert** [comment]
Hmmm... add is an old ProMotion "append-like" dsl

**Comment by cavalryjim** [comment]
Yes.  You gentlemen are correct.  I changed to 'append(FooView)' and all is well.   Thanks.

**Comment by squidpunch** [comment]
awesome, glad that was it! :)

**Comment by markrickert** [comment]
:+1:
