### ISSUE TITLE
customize section on a PM::TableScreen

### ISSUE THREAD

**Issue by soyoh** [clearsightstudio/ProMotion#720]
Hi,
i'm new to rubymotion (and redpotion of course), i'm trying to figure out if is possible to edit a section on a table view?? for example, make the text smaller or with more space, etc... is that even possible?

Thanks.

**Comment by kevinvangelder** [comment]
If you are looking to tweak the appearance of a section header, there is some information in this post: http://jamonholmgren.com/promotion-2-3-notable-changes/

If that's not enough customization for you, you'll need to implement a custom section header cell (subclassing UITableViewHeaderFooterView).

```ruby
{
  title: "Section Title",
  title_view: SectionTitle,
  cells: []
}
---
class SectionTitle < UITableViewHeaderFooterView
  def self.new
    cell = alloc.init
    # do custom stuff
    cell
  end
end
```

**Comment by soyoh** [comment]
Thats awesome! thanks for the help @kevinvangelder it works perfectly with "will_display_header"
