### ISSUE TITLE
How to style navigationbar??

### ISSUE THREAD

**Issue by soyoh** [clearsightstudio/ProMotion#721]
Hi guys,
i want to set a background color to the main navigation bar, i couldn't find anything on the documentation.
just found "tint_color" but i also want to set the background... is this possible anyhow?

Thanks.

**Comment by soyoh** [comment]
Found the solution.

i have to style it on each screen, not in app delegate

using something like:
```ruby
def on_load
    self.navigationController.navigationBar.translucent = false
    self.navigationController.navigationBar.barTintColor = rmq.color('A7DBD8')
end
```

is there any objection on adding this to the delegate module?? just like we can set the tint_color, would be nice if we can use this too...

Thanks!

**Comment by jamonholmgren** [comment]
Hey @soyoh ! You could use UIAppearance to do that in your app delegate, something like this:

```ruby
    UITabBar.appearance.setTranslucent(false)
    UITabBar.appearance.setTintColor(rmq.color("A7DBD8"))
    UITabBar.appearance.setBarTintColor(rmq.color("A7DBD8"))
```

**Comment by eliduke** [comment]
I tried that suggestion and it didn't work for me.

**Comment by soyoh** [comment]
@eliduke jamon sugestion didn't work for me neigther, what i endup doing is a custom module that i include where i want, also, i can put here methods that i want to reuse across screens, for example:


```ruby
module ProMotion
  module MyFunctions

    def apply_nav_styles
      if nav_bar?
        navigation_controller.navigationBar.translucent = false
        navigation_controller.navigationBar.barTintColor = color.main_color
        navigation_controller.navigationBar.setTitleTextAttributes({
          UITextAttributeTextColor => rmq.color.white
        })
      end
    end


    def nav_open(screen_class)
      app_delegate.menu.center_controller = screen_class.new(nav_bar: true)
    end

    def attach_menu_btn
      set_nav_bar_button :left, title: "Menu", action: :show_menu
    end

    def show_menu
      app_delegate.menu.toggle_left
    end

  end
end
```

then i include this file on a screen_x.rb and use like this:

```ruby
class my_screen < PM::Screen
  include PM::MyFuncitons
  def on_load
    apply_nav_styles
  end
end
```

**Comment by soyoh** [comment]
Even easier....

use the file appearance.rb included in PM

and put this there:

```ruby
UINavigationBar.appearance.tap do |o|
	o.translucent   = false
	o.barTintColor  = rmq.color.main_color
	o.tintColor     = rmq.color.white

	o.setTitleTextAttributes( {
		UITextAttributeTextColor => rmq.color.white
		#UITextAttributeTextShadowColor => color.clear
	})
end
```
