### ISSUE TITLE
Search is not filtering search results

### ISSUE THREAD

**Issue by andrewhavens** [clearsightstudio/ProMotion#724]
This seems really strange because I thought this had been working a few weeks ago...I just created this simple example, and the search results are not being filtered:

```
class AlphabetScreen < PM::TableScreen
  searchable placeholder: 'Search'

  def table_data
    [{
      cells: ('A'..'Z').map do |letter|
        {title: letter}
      end
    }]
  end
end
```

I'm currently using the master branch.

**Comment by markrickert** [comment]
Are you using redpotion? If so, use master on that as well until we release a new version.

**Comment by andrewhavens** [comment]
Oh, I see now:
* https://github.com/infinitered/redpotion/issues/138
* https://github.com/infinitered/redpotion/pull/135
