### ISSUE TITLE
Table cell :remote_image :size does not work

### ISSUE THREAD

**Issue by andrewhavens** [clearsightstudio/ProMotion#725]
[The docs](https://github.com/clearsightstudio/ProMotion/blob/master/docs/Reference/API%20Reference%20-%20ProMotion%20Table%20-%20Cell%20Options.md) mention that you can specify the size of the image within the `:remote_image` hash. I am not able to get this to work. I searched the codebase and it does not actually look like this is implemented. Am I wrong?

**Comment by jamonholmgren** [comment]
You're right.

![headdesk](http://media0.giphy.com/media/p8Uw3hzdAE2dO/giphy.gif)

https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/table/cell/table_view_cell_module.rb#L48-L73

**Comment by markrickert** [comment]
The best way i've found to change the image view's size is as follows:

```ruby
class CustomCell < PM::TableViewCell
  def on_load
  end

  def layoutSubviews
    super
    self.imageView.bounds = CGRectMake(0,0,40,40);
  end
end
```

**Comment by andrewhavens** [comment]
How was this intended to work? I'm specifically interested in the placeholder image because the one I'm using is too large. I'd rather not create a custom cell for this because it's so simple.

**Comment by jamonholmgren** [comment]
I think it's intended to take either a fixnum or array with two fixnums. Like this:

```ruby
size: [ 100, 80 ], # 100 w, 80 h
size: 50,          # 50 w, 50 h
```

**Comment by andrewhavens** [comment]
I mean, would this do something like:

```ruby
imageView.frame.size.width = data_cell[:remote_image][:size]
imageView.frame.size.height = data_cell[:remote_image][:size]
```

**Comment by markrickert** [comment]
If you use `bounds` instead of `frame`, the standard UITableViewCell will automatically center it for you :+1:

**Comment by andrewhavens** [comment]
Good to know. I'll work on a pull request for this. I'm curious...I've noticed lots of RubyMotion code that references `self` even when it is not necessary. I know this is required in Objective-C but I don't think it's necessary in RubyMotion. Is there a reason to adhere to this style?

**Comment by andrewhavens** [comment]
So I've tried implementing something like this, but it's not working:

```
    def set_remote_image
      # ...
      if data_cell[:remote_image][:size]
        size = data_cell[:remote_image][:size]
        size = [size, size] unless size.is_a? Array
        self.imageView.bounds = [[0, 0], size]
      end
    end
```

When I inspect the code, it looks correct, but it isn't affecting the size. When I apply this code in the REPL, it works and resizes the image. So it seems like maybe the image is being resized to the size of the image before it is rendered.

**Comment by andrewhavens** [comment]
Nevermind! Figured it out. See PR.

**Comment by jamonholmgren** [comment]
> I'm curious...I've noticed lots of RubyMotion code that references self even when it is not necessary. I know this is required in Objective-C but I don't think it's necessary in RubyMotion. Is there a reason to adhere to this style?

No particular reason, and I've really gone away from it lately. But most of ProMotion was written before that, so it's using `self.` everywhere. And I think Mark and Silas also followed that style.

These days, I use `self` when assigning properties and sometimes when the context is unclear (inside a block or something) to reference methods, but not much else.

**Comment by markrickert** [comment]
sooooo. I totally forgot I had done this, lol https://github.com/clearsightstudio/ProMotion/pull/707

@jamonholmgren When are you going to do a new merge batch and release?

**Comment by jamonholmgren** [comment]
Now!
