### ISSUE TITLE
Low resolution on device

### ISSUE THREAD

**Issue by divmgl** [clearsightstudio/ProMotion#737]
After `promotion new test`, running the application using `rake device` shows the app in a low resolution on an iPhone 6 Plus. Is anyone else getting this problem?

**Comment by squidpunch** [comment]
it's because the template doesnt have the default loading image for iphone6 6plus so they are scaling the app.  I'll send a PR

**Comment by squidpunch** [comment]
PR created: jamonholmgren/promotion-template#12

**Comment by jamonholmgren** [comment]
Thanks!
